backend:
  name: github
  repo: ajcfguinee-dev/ajcf-guinee
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projets"
    folder: "projects"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "team"
    label: "Équipe"
    folder: "team"
    create: true
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Fonction", name: "role", widget: "string" }
